default: &default
  adapter: postgresql
  encoding: unicode
  host: /tmp/
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homesteading-development

test:
  <<: *default
  database: homesteading-test
